CREATE TABLE Staff ( 
egn VARCHAR(10) NOT NULL,
phone VARCHAR(13) ,
dep INT NOT NULL,
bd DATE,
salary DOUBLE NOT NULL,
linear_manager VARCHAR(10),
PRIMARY KEY (egn) );

CREATE TABLE Dep ( 
dep_id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
name VARCHAR(120) NOT NULL,
office INT NOT NULL,
manager VARCHAR(10) NOT NULL,
PRIMARY KEY (dep_id) );

CREATE TABLE Zones( 
zone_id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
zone_floor INT NOT NULL,
zone_size DOUBLE,
PRIMARY KEY (zone_id));

CREATE TABLE Owners( 
owner_id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
name VARCHAR(250) NOT NULL,
phone VARCHAR(13),
email VARCHAR(120),
PRIMARY KEY (owner_id) );

CREATE TABLE Contracts( 
contracts_id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
peice DOUBLE NOT NULL,
owner INT NOT NULL,
--FOREIGN KEY REFERENCES Owners(owner_id),
 zone_id INT NOT NULL,
-- FOREIGN KEY REFERENCES Zones(zones_id),
 stdate DATE,
endate DATE,
PRIMARY KEY (contracts_id) );

ALTER TABLE STAFF FOREIGN KEY (dep) REFERENCES DEP (dep_id) ON
UPDATE
	NO ACTION ON
	DELETE
	CASCADE;

ALTER TABLE OWNERS ADD CONSTRAINT EMAIL CHECK (EMAIL LIKE '%@%.%');

ALTER TABLE OWNERS ADD CONSTRAINT PHONE CHECK (PHONE LIKE '[0-9]');

ALTER TABLE STAFF ADD CONSTRAINT PHONE CHECK (PHONE LIKE '[0-9]');

ALTER TABLE STAFF ADD CONSTRAINT SALARY CHECK (SALARY >= 0.0);

ALTER TABLE STAFF FOREIGN KEY (linear_manager) REFERENCES STAFF (egn);

ALTER TABLE DEP FOREIGN KEY (office) REFERENCES ZONES (zone_id);

ALTER TABLE DEP FOREIGN KEY (manager) REFERENCES STAFF (egn);

ALTER TABLE CONTRACTS FOREIGN KEY (owner) REFERENCES OWNERS (owner_id);

ALTER TABLE CONTRACTS FOREIGN KEY (zone_id) REFERENCES ZONES (zone_id);

CREATE FUNCTION DEPTSTAFF (DEPNAME VARCHAR(120))
     RETURNS TABLE (EGN VARCHAR(10),
                    SALARY DOUBLE)
     LANGUAGE SQL
     READS SQL DATA
     NO EXTERNAL ACTION
     DETERMINISTIC
     RETURN
       SELECT EGN, SALARY
         FROM (SELECT * FROM STAFF RIGHT JOIN DEP ON STAFF.DEP = DEP_ID) AS SD
         WHERE SD.NAME = DEPNAME

-- Parking spots          
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (0, 20.00);

INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (1, 120.22);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (1, 120.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (1, 60.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (2, 300.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (2, 222.22);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (2, 166.69);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (3, 100.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (3, 100.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (3, 100.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (3, 50.00);
INSERT INTO ZONES (ZONE_FLOOR , ZONE_SIZE) VALUES (3, 50.00);

INSERT INTO OWNERS (NAME, PHONE, EMAIL ) VALUES ('Billa', '1234567890', 'billamanager@billa.com');
INSERT INTO OWNERS (NAME, PHONE, EMAIL ) VALUES ('Lilly', '2455342452', 'lillydrugs@lilly.com');
INSERT INTO OWNERS (NAME, PHONE, EMAIL ) VALUES ('DB', '3523424213', 'dbmanagement@dm.com');
INSERT INTO OWNERS (NAME, PHONE, EMAIL ) VALUES ('fibank', '3453253523', 'fibankmanager@fibank.com');
INSERT INTO OWNERS (NAME, PHONE, EMAIL ) VALUES ('CROP', '4206942069', 'CROP@dope.com');

INSERT INTO STAFF (EGN, DEP, SALARY ) VALUES ('9876453281', 1, 888.888);
